//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 6.2.1.
// BinEdit_res.rc

#define IDD_GOTO_OFFSET                     100

#define IDR_BINEDIT_CTX_MENU                100

#define ID_EDIT                             100
#define ID_ANSI                             101
#define ID_UTF8                             102
#define ID_UTF16                            103
#define ID_EXIT                             104
#define ID_FILE_OPEN                        105
#define ID_TOGGLE_HEADER                    106
#define ID_BINEDIT_CUT                      107
#define ID_BINEDIT_COPY                     108
#define ID_BINEDIT_PASTE                    109
#define ID_BINEDIT_DELETE                   110
#define ID_BINEDIT_SELECTALL                111
#define ID_BINEDIT_ANSI                     112
#define ID_BINEDIT_UTF8                     113
#define ID_BINEDIT_UTF16                    114
#define ID_BINEDIT_SJIS                     115
#define ID_BINEDIT_GOTO                     116
#define ID_BINEDIT_COPYDUMPTEXT             117

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     118
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
